### ISSUE TITLE
fast ECM

### ISSUE THREAD

**Issue by Dr-WangL** [amwink/bias#1]
I want to use the fECM package based-on MATLAB to process data, but there was something wrong when it works as follow: 
 **Undefined function 'backbone_wu' for input arguments of type 'double'.

Error in fastECM (line 463)
	[mst clus] = backbone_wu (no0corr, fix (sqrt (lv) ) );

Error in fegui>doecm (line 386)
        cmdlog = evalc('fastECM(opts);');
 
Error while evaluating UIControl Callback**

I don't know how to solve this problem, and I have some questions to understand the message in the file named ‘fastECM.pdf’.
Thanks very much!

**Comment by amwink** [comment]
Dear Dr-WangL,

A number of external scripts are used in atlas mode, to compute graph metrics. These can be downloaded from the brain connectivity toolbox, https://sites.google.com/site/bctnet

In Linux this can be done automatically with a command line tool called wget. If you don't have Linux, or don't have where installed, I'm afraid you need to do that manually.

One of them is called
   backbone_wu.m,
the others are
   community_louvain.m,
   betweenness_bin.m,
   clustering_coef_bu.m and
   distance_bin.m
which need to be in the same directory as fastECM.m

The example files have also changed I'm afraid, the new URL is https://drive.google.com/file/d/0B_HPbdIK_1BacC12T0R3UTdLRVE/view?usp=drivesdk

Hope that helps!

bw
Alle Meije
________________________________
